name: Feature Request
description: Suggest a new feature for the Discovery Agent
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: service
    attributes:
      label: Related Service
      description: Which service would this feature affect?
      options:
        - Network Scanner (Go)
        - Code Analyzer (Python)
        - Database Inspector (Python)
        - Event Bus / RabbitMQ
        - Enrichment Pipeline
        - PII Redactor
        - Approval API
        - Approval UI
        - Transmitter
        - New Collector
        - Infrastructure / DevOps
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Should have
        - Must have
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
